
name: CI/CD pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ dev ]

defaults:
  run:
    working-directory: app

jobs:
  ESLint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm run eslint
